### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by robled** [bagrat/vim-workspace#2]
Would it be possible to enable buffer selection through the tab bar with the mouse when `set mouse+=a` is configured?

**Comment by bagrat** [comment]
@robled are you using Vim or NeoVim?

In Vim in will unfortunately not be possible, but there should be a way to do that in NeoVim. I am currently looking at NeoVim options.

**Comment by bagrat** [comment]
@robled just added mouse support (https://github.com/bagrat/vim-workspace/commit/7c8ed92e70d85919d11b8e605247206a408a2f3c):

* Vim - click support for tabpagess only (due to Vim limitations)
* NeoVim - click support for tabpages, buffers and truncated items. When clicking on the truncated item (arrow and number of truncated buffers), it takes you to the first truncated buffer on the left/right

Please let me know, if this works for you.

**Comment by robled** [comment]
Thanks for adding this feature.  I am using vim 8.0.596 and I tested the latest master branch as of the time of this post.  To me, the behavior is unchanged from before, in that if I left-click on the tab bar vim just opens a new empty buffer rather than switching to the buffer that I left-clicked on in the tab bar.

Steps to reproduce:

1.  Open at least two buffers and you can see two filenames in the tab bar.
2.  Left-click on a buffer in the tab bar that's not active.  Rather than switching to the inactive buffer, a new, empty buffer is created.

**Comment by bagrat** [comment]
@robled that's interesting, cause I cannot reproduce it with single left-click. When I do double-left-click anywhere in the tabline, Vim creates a new tabpage, which is from inside Vim, and not under the plugin's control. However, when I left-click on a tabpage, it switches to that tabpage.

Regarding switching buffers, as I have already commented, unfortunately that is not possible in Vim, as opposed to NeoVim 😕 

Thanks and feel free to shoot other issues whenever you face any.
